services:
  - type: web
    name: redrob-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/streamlit_app.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    healthCheckPath: /_stcore/health
    autoDeploy: true
